name: switchkeys
description: Streamline feature flag management. Effortlessly toggle features for A/B testing, phased rollouts & rapid experimentation. Drive innovation with ease.
version: 1.0.4
repository: https://github.com/Mahmoud-Emad/Switchkeys

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  json_annotation: ^4.0.0
  json_serializable: ^6.7.1
  logging: ^1.2.0
  ini: ^2.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  build_runner: ^2.1.1
