# version: "3"

services:
  postgres_db:
    image: postgres:latest
    container_name: switchkey-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - switchkey-network

  backend:
    build:
      context: ../
      dockerfile: ./docker/backend.Dockerfile
    container_name: switchkey-backend
    ports:
      - "8000:8000"
    environment:
      # Backend configurations
      - ENV=${ENV}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}

      # Servers configurations
      - SERVER_DOMAIN_NAME=${SERVER_DOMAIN_NAME}

      # Database configurations
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=postgres_db

    depends_on:
      - postgres_db
    networks:
      - switchkey-network

volumes:
  postgres_data:

networks:
  switchkey-network:
